(()=>{
'use strict';
const URL='https://csbgmzfvwqwhcbvvhgxw.supabase.co';
const KEY='sb_publishable_-Yq8Zt1tR2Kll07EXuKavA_yX4I56H3';
const H={apikey:KEY,Authorization:'Bearer '+KEY};
let current=null,owned='standard',hooked=false,seq=0,tierRows=[];
const paid=t=>t==='obsidian'||t==='gold';
const zh=()=>document.documentElement.lang!=='en';
function addCss(){if(document.getElementById('ig-upgrade-css'))return;const s=document.createElement('style');s.id='ig-upgrade-css';s.textContent=`
body:not(.memorial-mode){background:radial-gradient(circle at top,#1a1a17 0,#0d100d 46%)!important}
body:not(.memorial-mode) #graveyard .grave{background:#151814!important;border-color:#383a32!important;box-shadow:none!important}
body:not(.memorial-mode) #graveyard .grave:hover{border-color:#56584f!important}
body:not(.memorial-mode) #graveyard .grave.recently-resurrected:not(.ig-paid-obsidian):not(.ig-paid-gold){border-color:#4f8a5d!important;box-shadow:0 0 0 1px rgba(104,190,124,.12),0 0 22px rgba(78,160,98,.13)!important}
body:not(.memorial-mode) #graveyard .grave.ig-paid-obsidian{position:relative!important;overflow:hidden!important;border:3px solid #d8e0e4!important;background:linear-gradient(135deg,#24282b 0%,#090b0c 52%,#010202 100%)!important;box-shadow:inset 0 0 0 1px #5c656a,0 0 0 1px #0c0e0f,0 0 28px rgba(220,230,235,.34)!important}
body:not(.memorial-mode) #graveyard .grave.ig-paid-obsidian::before{content:'◆ BLACK OBSIDIAN';position:absolute;right:15px;top:14px;z-index:6;padding:6px 10px;border:1px solid #c9d2d7;border-radius:999px;background:#030404;color:#f0f4f6;font:900 9px/1 Inter,system-ui,sans-serif;letter-spacing:.11em}
body:not(.memorial-mode) #graveyard .grave.ig-paid-obsidian::after{content:'';position:absolute;inset:0;pointer-events:none;z-index:1;background:linear-gradient(115deg,transparent 0 39%,rgba(255,255,255,.11) 48%,transparent 57%)}
body:not(.memorial-mode) #graveyard .grave.ig-paid-obsidian .stone{filter:grayscale(1) brightness(1.45);text-shadow:0 0 16px rgba(225,235,240,.38)}
body:not(.memorial-mode) #graveyard .grave.ig-paid-obsidian h3{color:#f2f5f6!important}
body:not(.memorial-mode) #graveyard .grave.ig-paid-gold{position:relative!important;overflow:hidden!important;border:3px solid #edc75f!important;background:linear-gradient(135deg,#3a2e10 0%,#151005 52%,#040301 100%)!important;box-shadow:inset 0 0 0 1px #826725,0 0 0 1px #1e1605,0 0 30px rgba(237,199,95,.36)!important}
body:not(.memorial-mode) #graveyard .grave.ig-paid-gold::before{content:'✦ GOLD MONUMENT';position:absolute;right:15px;top:14px;z-index:6;padding:6px 10px;border:1px solid #edc75f;border-radius:999px;background:#211907;color:#ffe39a;font:900 9px/1 Inter,system-ui,sans-serif;letter-spacing:.11em}
body:not(.memorial-mode) #graveyard .grave.ig-paid-gold h3{color:#ffe39a!important}
#detailDialog .detail-grave.ig-detail-obsidian{padding:22px!important;border:4px double #d8e0e4!important;outline:1px solid #5c656a!important;outline-offset:-8px!important;border-radius:18px!important;background:linear-gradient(145deg,#202427,#070909 60%,#010202)!important;box-shadow:0 0 34px rgba(218,226,230,.24)!important}
#detailDialog .detail-grave.ig-detail-gold{padding:22px!important;border:4px double #edc75f!important;outline:1px solid #806425!important;outline-offset:-8px!important;border-radius:18px!important;background:linear-gradient(145deg,#392d10,#100c04 60%,#030201)!important;box-shadow:0 0 38px rgba(237,196,91,.30)!important}
.ig-badge{display:table;margin:2px auto 14px;padding:7px 14px;border-radius:999px;font-size:11px;font-weight:900;letter-spacing:.12em}.ig-badge.obsidian{background:#020303;border:1px solid #c3cbd0;color:#e8edef}.ig-badge.gold{background:#211907;border:1px solid #e3bb55;color:#f4d478}
.ig-entry{margin-top:16px;padding:16px;border:1px solid #383a32;border-radius:14px;background:#101310;text-align:center}.ig-entry b{display:block;margin-bottom:5px}.ig-entry p{margin:0 0 12px;color:#9da79f;font-size:12px}.ig-entry button{border:1px solid #5c5f56;border-radius:10px;background:#eeeae0;color:#111;padding:11px 15px;font-weight:850;cursor:pointer}
.ig-modal{border:1px solid #45483f;border-radius:18px;background:#101310;color:#f3f0e7;width:min(720px,calc(100% - 24px));padding:22px}.ig-modal::backdrop{background:#000c}.ig-head{display:flex;justify-content:space-between;gap:16px}.ig-head h2{margin:0 0 6px;font:700 25px Georgia,serif}.ig-head p{margin:0;color:#9da79f;font-size:13px}.ig-close{border:0;background:transparent;color:#aab3aa;font-size:24px;cursor:pointer}.ig-tiers{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:18px}.ig-tier{border:1px solid #3d4038;background:#141714;border-radius:14px;padding:16px;text-align:left;color:#f3f0e7;cursor:pointer}.ig-tier strong{display:block}.ig-price{font-size:21px;font-weight:900;margin:8px 0}.ig-tier small{color:#9da79f;line-height:1.5}.ig-tier.sel{outline:3px solid #ece8dd}.ig-tier[data-tier=obsidian]{background:linear-gradient(145deg,#202326,#050606);border-color:#c3cbd0}.ig-tier[data-tier=gold]{background:linear-gradient(145deg,#30250d,#0c0904);border-color:#e3bb55}.ig-tier[data-tier=gold] strong,.ig-tier[data-tier=gold] .ig-price{color:#f4d478}.ig-pay{width:100%;margin-top:14px;border:0;border-radius:11px;padding:13px;font-weight:900;background:#eeeae0;color:#111}.ig-pay:disabled{opacity:.58}.ig-note{text-align:center;color:#88938a;font-size:11px;margin-top:9px}@media(max-width:700px){.ig-tiers{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function detailPaint(tier){const d=document.querySelector('#detailDialog .detail-grave');if(!d)return;d.classList.remove('ig-detail-obsidian','ig-detail-gold');document.getElementById('ig-badge')?.remove();if(!paid(tier))return;d.classList.add('ig-detail-'+tier);const name=document.getElementById('detailName');if(name){const b=document.createElement('div');b.id='ig-badge';b.className='ig-badge '+tier;b.textContent=tier==='gold'?'✦ GOLD MONUMENT':'◆ BLACK OBSIDIAN';name.parentElement?.insertBefore(b,name)}}
async function tierFor(id){const n=++seq;try{const r=await fetch(`${URL}/rest/v1/graves?id=eq.${encodeURIComponent(id)}&select=monument_tier`,{headers:H});const a=await r.json();if(n!==seq)return;owned=paid(a?.[0]?.monument_tier)?a[0].monument_tier:'standard';detailPaint(owned)}catch(e){if(n===seq){owned='standard';detailPaint('standard')}}}
function owner(){if(current?.graveType==='memorial')return false;try{return !!(current&&window.getOwnerToken?.(current.id))}catch(e){return false}}
function mount(){document.querySelectorAll('#ig10-entry,#ig-v9-entry,#ig-v8-entry,#ig-v7-entry,#ig-v6-entry,#ig-v5-entry,#ig-v4-entry').forEach(x=>x.remove());let e=document.getElementById('ig-entry');if(!owner()){e?.remove();return}if(e)return;const a=document.getElementById('ownerActionsLabel');if(!a?.parentElement)return;e=document.createElement('div');e.id='ig-entry';e.className='ig-entry';e.innerHTML=`<b>${zh()?'讓這座墓碑更有存在感':'Make this grave stand out'}</b><p>${zh()?'現在或之後都能升級。標準版永久免費。':'Upgrade now or later. Standard stays free forever.'}</p><button type="button">${zh()?'查看 / 升級墓碑樣式':'View / upgrade grave style'}</button>`;e.querySelector('button').onclick=openUpgrade;a.parentElement.appendChild(e)}
function modal(){let d=document.getElementById('ig-modal');if(d)return d;d=document.createElement('dialog');d.id='ig-modal';d.className='ig-modal';d.innerHTML='<div class="ig-head"><div><h2></h2><p></p></div><button class="ig-close">×</button></div><div class="ig-tiers"></div><button class="ig-pay"></button><div class="ig-note"></div>';d.querySelector('.ig-close').onclick=()=>{detailPaint(owned);d.close()};document.body.appendChild(d);return d}
function openUpgrade(){const d=modal(),z=zh(),tiers=d.querySelector('.ig-tiers'),pay=d.querySelector('.ig-pay');d.querySelector('h2').textContent=z?'讓這座墓碑更特別':'Make this grave more special';d.querySelector('.ig-head p').textContent=z?'已購買等級會永久保存；其他等級只是預覽。':'Purchased tier is permanent; other tiers are preview only.';tiers.innerHTML=`<button class="ig-tier" data-tier="standard"><strong>🪦 ${z?'標準墓碑':'Standard Grave'}</strong><div class="ig-price">FREE</div><small>${z?'完整墓碑、永久網址、分享與致意。':'Full grave, permanent URL, sharing and respects.'}</small></button><button class="ig-tier" data-tier="obsidian"><strong>◆ ${z?'黑曜墓碑':'Obsidian Grave'}</strong><div class="ig-price">US$2.99</div><small>${z?'深黑石材、銀灰金屬框與黑曜徽章。':'Deep black stone, silver frame and obsidian badge.'}</small></button><button class="ig-tier" data-tier="gold"><strong>✦ ${z?'黃金墓碑':'Gold Grave'}</strong><div class="ig-price">US$6.99</div><small>${z?'黑金石材、金色雙框與典藏徽章。':'Black-gold stone, gold frame and collector badge.'}</small></button>`;const sel=x=>{tiers.querySelectorAll('.ig-tier').forEach(b=>b.classList.toggle('sel',b.dataset.tier===x));detailPaint(x);if(x===owned){pay.disabled=true;pay.textContent=x==='obsidian'?(z?'目前擁有：黑曜墓碑 · 已永久升級':'Owned: Obsidian Grave · Permanent'):x==='gold'?(z?'目前擁有：黃金墓碑 · 已永久升級':'Owned: Gold Grave · Permanent'):(z?'目前：標準墓碑 · FREE':'Current: Standard Grave · FREE')}else if(x==='obsidian'){pay.disabled=false;pay.textContent=z?'預覽黑曜墓碑 · 永久升級 US$2.99':'Preview Obsidian · Upgrade US$2.99'}else if(x==='gold'){pay.disabled=false;pay.textContent=z?'預覽黃金墓碑 · 永久升級 US$6.99':'Preview Gold · Upgrade US$6.99'}else{pay.disabled=true;pay.textContent=z?'標準墓碑 · FREE':'Standard Grave · FREE'}};tiers.querySelectorAll('.ig-tier').forEach(b=>b.onclick=()=>sel(b.dataset.tier));pay.onclick=()=>window.showToast?.(z?'付款功能下一步接上；現在只測永久外觀。':'Payment comes next; testing appearance now.');d.querySelector('.ig-note').textContent=z?'預覽不代表已購買 · 一次付款 · 永久升級':'Preview is not a purchase · One-time payment · Permanent';sel(owned);d.showModal()}
async function loadPaid(){try{const r=await fetch(`${URL}/rest/v1/graves?grave_type=eq.project&select=id,type_number,name,epitaph,monument_tier&monument_tier=in.(obsidian,gold)&order=created_at.desc`,{headers:H});if(r.ok)tierRows=await r.json()}catch(e){console.warn('premium graves',e)}}
function signature(card){return {name:(card.querySelector('h3')?.textContent||'').trim(),epitaph:(card.querySelector('.epitaph')?.textContent||'').replace(/[“”"]/g,'').trim()}}
function matchRow(card){const s=signature(card);let rows=tierRows.filter(r=>String(r.name||'').trim()===s.name);if(rows.length===1)return rows[0];if(rows.length>1){const exact=rows.filter(r=>String(r.epitaph||'R.I.P.').trim()===s.epitaph);if(exact.length===1)return exact[0]}return null}
function paintCards(){if(document.body.classList.contains('memorial-mode'))return;document.querySelectorAll('#graveyard .grave').forEach(card=>{card.classList.remove('ig-paid-obsidian','ig-paid-gold','ig10-obsidian','ig10-gold','ig12-obsidian','ig12-gold','ig13-obsidian','ig13-gold');card.querySelectorAll('.ig10-tag,.ig-v9-card-tag,.ig-v8-card-tag,.ig-v7-card-tag').forEach(x=>x.remove());const r=matchRow(card);if(paid(r?.monument_tier))card.classList.add('ig-paid-'+r.monument_tier)})}
async function refreshCards(){await loadPaid();paintCards()}
function hook(){if(hooked||typeof window.fillDetail!=='function')return false;const old=window.fillDetail;window.fillDetail=function(g){current=g||null;const r=old.apply(this,arguments);if(g?.id)tierFor(g.id);setTimeout(mount,0);return r};hooked=true;return true}
function start(){addCss();hook();let tries=0;const h=setInterval(()=>{if(hook()||++tries>40)clearInterval(h)},100);setInterval(mount,500);refreshCards();const gy=document.getElementById('graveyard');if(gy)new MutationObserver(()=>setTimeout(paintCards,20)).observe(gy,{childList:true});setInterval(refreshCards,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();